spring:
  application:
    name: register-manager
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://postgresdb:5432/register_manager}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: none
    properties:
      hibernate.format_sql: true
  test:
    enabled: false
server:
  port: 8081
app:
  session:
    expirationtime: ${EXPIRATION_TIME:30}


viacep:
  url:  ${VIA_CEP_URL:https://viacep.com.br/ws/}