spring:
  application:
    name: register-manager
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/register_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: none
    properties:
      hibernate.format_sql: true
  test:
    enabled: false
server:
  port: 8081
app:
  session:
    expirationtime: 2


viacep:
  url:  https://viacep.com.br/ws/